version: "3.8"

services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: ghcr.io/joshuaavalon/cloudflare-ddns:latest

    networks:
      - web

    volumes:
      - ./config/config.yaml:/app/config.yaml

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

    restart: unless-stopped
