version: "3.8"

services:
  actual-budget:
    container_name: actual-budget
    image: actualbudget/actual-server:latest

    env_file:
      - ../.env
      - .env

    user: "${PUID}:${PGID}"

    security_opt:
      - no-new-privileges

    volumes:
      - ${DOCKER_DATA_LOCATION}/actual-budget:/data

    labels:
      - docker-volume-backup.stop-during-backup=true

    restart: unless-stopped