version: "3.8"

services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:v1.0.0-RC1.1

    # Without defining this user Mealie creates files as a root user
    user: "${PUID}:${PGID}"

    security_opt:
      - no-new-privileges

    networks:
      - web

    ports:
      - ${PORT}:9000

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      ALLOW_SIGNUP: ${ALLOW_SIGNUP}
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: ${PUBLIC_URL}

    volumes:
      - ./data:/app/data

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

    restart: unless-stopped