version: "3.8"

services:
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest

    env_file:
      - ../.env
      - .env

    volumes:
      - ${DOCKER_DATA_LOCATION}/duplicati:/config
      - ${BACKUP_LOCATION}:/backups
      - ${DOCKER_DATA_LOCATION}:/source/docker-data
      - ${STORAGE_LOCATION}:/source/storage

    restart: unless-stopped