---
# Homepage configuration

title: "Dashboard"
subtitle: "Homelab"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

# Theme customization
theme: default
colors:
  light:
    highlight-primary: "#e6e6e6"
    highlight-secondary: "#f8f8f8"
    highlight-hover: "#d8d5d5"
    background: "#f8f8f8"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#9a9a9a"
    text-title: "#0A090B"
    text-subtitle: "#4F4D55"
    card-shadow: rgba(10, 9, 11, 0.05)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#505050"
    highlight-secondary: "#131313"
    highlight-hover: "#b4b4b4"
    background: "#131313"
    card-background: "#252525"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Navbar
links: []

# Services
services:
  - name: "Group 1"
    items:
      - name: "Service 1"
        subtitle: "Description"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/example.png"
        url: "http://application-url"