version: "3.8"

services:
  home-assistant:
    container_name: home-assistant
    image: lscr.io/linuxserver/homeassistant:latest

    network_mode: host # To enable automatic discovery of new devices

    ports:
      - ${PORT}:8123

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOCKER_MODS: linuxserver/mods:homeassistant-hacs

    volumes:
      - ./config:/config

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

    restart: unless-stopped