version: "3.8"

services:
  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    env_file:
      - ../.env
      - .env

    user: "${PUID}:${PGID}"

    depends_on:
      - immich-redis
      - immich-database
      - immich-typesense

    command: [ "start.sh", "immich" ]

    volumes:
      - ${STORAGE_LOCATION}/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    env_file:
      - ../.env
      - .env

    user: "${PUID}:${PGID}"

    depends_on:
      - immich-redis
      - immich-database
      - immich-typesense

    command: [ "start.sh", "microservices" ]

    volumes:
      - ${DOCKER_DATA_LOCATION}/immich-machine-learning-gecoding:/usr/src/app/.reverse-geocoding-dump
      - ${STORAGE_LOCATION}/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

#    extends:
#      file: hwaccel.yml
#      service: hwaccel

    restart: unless-stopped

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}

    env_file:
      - ../.env
      - .env

    user: "${PUID}:${PGID}"

    volumes:
      - ${DOCKER_DATA_LOCATION}/immich-machine-learning:/cache

    restart: unless-stopped

  immich-typesense:
    container_name: immich-typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd

    user: "${PUID}:${PGID}"

    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1

    volumes:
      - ${DOCKER_DATA_LOCATION}/immich-typesense:/data

    restart: unless-stopped

  immich-redis:
    container_name: immich-redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5

    user: "${PUID}:${PGID}"

    volumes:
      - ${DOCKER_DATA_LOCATION}/immich-redis:/data

    restart: unless-stopped

  immich-database:
    container_name: immich-database
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad

    env_file:
      - ../.env
      - .env

    user: "${PUID}:${PGID}"

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}

    volumes:
      - ${DOCKER_DATA_LOCATION}/immich-database:/var/lib/postgresql/data

    restart: unless-stopped