version: "3.8"

services:
  homebox:
    container_name: homebox
    image: ghcr.io/hay-kot/homebox:latest-rootless

    user: "${PUID}:${PGID}"

    security_opt:
      - no-new-privileges

    networks:
      - web

    ports:
      - ${PORT}:7745

    environment:
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_UPLOAD_SIZE: 100
      HBOX_OPTIONS_ALLOW_REGISTRATION: ${ALLOW_REGISTRATION}

    volumes:
      - ./data:/data

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

    restart: unless-stopped