version: "3.8"

services:
  homer:
    container_name: homer
    image: b4bz/homer

    user: "${PUID}:${PGID}"

    security_opt:
      - no-new-privileges

    networks:
      - web

    ports:
      - ${PORT_HOMER}:8080

    environment:
      - IPV6_DISABLE=${DISABLE_IPV6}

    volumes:
      - ./assets:/www/assets

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

    restart: unless-stopped