version: "3.8"

services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest

    networks:
      - web

    ports:
      - ${PORT}:8096
      - 7359:7359/udp # Optional - Allows clients to discover Jellyfin on the local network.
      - 1900:1900/udp # Optional - Service discovery used by DNLA and clients.

    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      JELLYFIN_PublishedServerUrl: ${SERVER_IP}
      DOCKER_MODS: linuxserver/mods:jellyfin-opencl-intel

    volumes:
      - ./config:/config
      - ${MEDIADIR}:/data

    devices:
      - /dev/dri:/dev/dri

    restart: unless-stopped