version: "3.8"

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest

    networks:
      - web

    ports:
      - ${PORT}:8080

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M

    restart: unless-stopped